### ISSUE TITLE
Re Dead Project

### ISSUE THREAD

**Issue by binarymist** [embark-framework/neo-blessed#6]
Re: [Dead Project](https://github.com/chjj/blessed/issues/346#issuecomment-403161932): Can we assume you have a vested interest in this project?

Re: 

> We have a fork called neo-blessed that is meant to be a drop-in replacement and maintained.

I'm not seeing much in the way of work being done on this project, am I missing something?
Can you please share your plan/roadmap with the community?
Thanks.

**Comment by binarymist** [comment]
Any update @iurimatias?

**Comment by iurimatias** [comment]
Hi @binarymist!
Thanks for asking this. In short, Our main project [Embark](https://github.com/embark-framework/embark) & its users depend on Blessed being maintained and working well. So it's in our best interest to do so.
Initially we'll merge pending bug fixes first long overdue. At some point we will be refactoring some code and only then add new features.

**Comment by binarymist** [comment]
Thanks @iurimatias, I'm building a core omponent using blessed also, please continue to keep the community up to date as you move forward.
May even be worth keeping this open or something similar where the community can review progress as it occurs?
